default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: philo_development

test:
  <<: *default
  database: philo_test

production:
  <<: *default
  database: philo_production
  username: philo
  password: <%= ENV['PHILO_DATABASE_PASSWORD'] %>
